import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const ROLE_MAPPINGS: Record<string, string> = {
  'admin@swaatienterprises.in': 'ADMIN',
  'amit.verma@swaatienterprises.in': 'OPERATION_HEAD',
  'rajesh.sharma@swaatienterprises.in': 'SALES',
  'pooja.sawant@swaatienterprises.in': 'SALES',
  'sanjay.kulkarni@swaatienterprises.in': 'OPERATION_HEAD',
  'patilrohan1996@gmail.com': 'OPERATION_HEAD',
};

const PERMISSIONS_BY_ROLE: Record<string, Record<string, boolean>> = {
  ADMIN: {
    dashboard: true,
    'dashboard.view': true,
    attendance: true,
    'attendance.view_own': true,
    'attendance.checkin': true,
    'attendance.view_team': true,
    'attendance.edit': true,
    'attendance.approve': true,
    leave: true,
    'leave.view_own': true,
    'leave.apply': true,
    'leave.view_team': true,
    'leave.approve': true,
    'leave.reject': true,
    'leave.cancel': true,
    tasks: true,
    'tasks.view_own': true,
    'tasks.view_team': true,
    'tasks.create': true,
    'tasks.assign': true,
    'tasks.edit': true,
    'tasks.status': true,
    'tasks.comments': true,
    'tasks.delete': true,
    leads: true,
    'leads.view': true,
    'leads.create': true,
    'leads.edit': true,
    'leads.status': true,
    'leads.assign': true,
    'leads.delete': true,
    products: true,
    'products.view': true,
    'products.create': true,
    'products.edit': true,
    'products.delete': true,
    notifications: true,
    'notifications.view': true,
    'notifications.read': true,
    messaging: true,
    'messaging.view': true,
    'messaging.send': true,
    'messaging.create_group': true,
    'messaging.attachments': true,
    reports: true,
    'reports.view': true,
    'reports.export': true,
    'payroll.view': true,
    'payroll.manage': true,
  },
  OPERATION_HEAD: {
    dashboard: true,
    'dashboard.view': true,
    attendance: true,
    'attendance.view_own': true,
    'attendance.checkin': true,
    'attendance.view_team': true,
    'attendance.edit': true,
    'attendance.approve': true,
    leave: true,
    'leave.view_own': true,
    'leave.apply': true,
    'leave.view_team': true,
    'leave.approve': true,
    'leave.reject': true,
    'leave.cancel': true,
    tasks: true,
    'tasks.view_own': true,
    'tasks.view_team': true,
    'tasks.create': true,
    'tasks.assign': true,
    'tasks.edit': true,
    'tasks.status': true,
    'tasks.comments': true,
    'tasks.delete': false,
    leads: true,
    'leads.view': true,
    'leads.create': true,
    'leads.edit': true,
    'leads.status': true,
    'leads.assign': true,
    'leads.delete': false,
    products: true,
    'products.view': true,
    'products.create': false,
    'products.edit': false,
    'products.delete': false,
    notifications: true,
    'notifications.view': true,
    'notifications.read': true,
    messaging: true,
    'messaging.view': true,
    'messaging.send': true,
    'messaging.create_group': true,
    'messaging.attachments': true,
    reports: true,
    'reports.view': true,
    'reports.export': true,
    'payroll.view': false,
    'payroll.manage': false,
  },
  SALES: {
    dashboard: true,
    'dashboard.view': true,
    attendance: true,
    'attendance.view_own': true,
    'attendance.checkin': true,
    'attendance.view_team': false,
    'attendance.edit': true,
    'attendance.approve': false,
    leave: true,
    'leave.view_own': true,
    'leave.apply': true,
    'leave.view_team': false,
    'leave.approve': false,
    'leave.reject': false,
    'leave.cancel': true,
    tasks: true,
    'tasks.view_own': true,
    'tasks.view_team': false,
    'tasks.create': false,
    'tasks.assign': false,
    'tasks.edit': false,
    'tasks.status': true,
    'tasks.comments': true,
    'tasks.delete': false,
    leads: true,
    'leads.view': true,
    'leads.create': true,
    'leads.edit': true,
    'leads.status': true,
    'leads.assign': false,
    'leads.delete': false,
    products: true,
    'products.view': true,
    'products.create': false,
    'products.edit': false,
    'products.delete': false,
    notifications: true,
    'notifications.view': true,
    'notifications.read': true,
    messaging: true,
    'messaging.view': true,
    'messaging.send': true,
    'messaging.create_group': false,
    'messaging.attachments': true,
    reports: false,
    'reports.view': false,
    'reports.export': false,
    'payroll.view': false,
    'payroll.manage': false,
  },
  ACCOUNTANT: {
    dashboard: true,
    'dashboard.view': true,
    attendance: true,
    'attendance.view_own': true,
    'attendance.checkin': true,
    'attendance.view_team': false,
    'attendance.edit': true,
    'attendance.approve': false,
    leave: true,
    'leave.view_own': true,
    'leave.apply': true,
    'leave.view_team': false,
    'leave.approve': false,
    'leave.reject': false,
    'leave.cancel': true,
    tasks: true,
    'tasks.view_own': true,
    'tasks.view_team': false,
    'tasks.create': false,
    'tasks.assign': false,
    'tasks.edit': false,
    'tasks.status': true,
    'tasks.comments': true,
    'tasks.delete': false,
    leads: false,
    'leads.view': false,
    'leads.create': false,
    'leads.edit': false,
    'leads.status': false,
    'leads.assign': false,
    'leads.delete': false,
    products: false,
    'products.view': false,
    'products.create': false,
    'products.edit': false,
    'products.delete': false,
    notifications: true,
    'notifications.view': true,
    'notifications.read': true,
    messaging: true,
    'messaging.view': true,
    'messaging.send': true,
    'messaging.create_group': false,
    'messaging.attachments': true,
    reports: true,
    'reports.view': false,
    'reports.export': true,
    'payroll.view': true,
    'payroll.manage': false,
  },
  WAREHOUSE_MANAGER: {
    dashboard: true,
    'dashboard.view': true,
    attendance: true,
    'attendance.view_own': true,
    'attendance.checkin': true,
    'attendance.view_team': false,
    'attendance.edit': true,
    'attendance.approve': false,
    leave: true,
    'leave.view_own': true,
    'leave.apply': true,
    'leave.view_team': false,
    'leave.approve': false,
    'leave.reject': false,
    'leave.cancel': true,
    tasks: true,
    'tasks.view_own': true,
    'tasks.view_team': false,
    'tasks.create': false,
    'tasks.assign': false,
    'tasks.edit': false,
    'tasks.status': true,
    'tasks.comments': true,
    'tasks.delete': false,
    leads: false,
    'leads.view': false,
    'leads.create': false,
    'leads.edit': false,
    'leads.status': false,
    'leads.assign': false,
    'leads.delete': false,
    products: true,
    'products.view': true,
    'products.create': true,
    'products.edit': true,
    'products.delete': false,
    notifications: true,
    'notifications.view': true,
    'notifications.read': true,
    messaging: true,
    'messaging.view': true,
    'messaging.send': true,
    'messaging.create_group': false,
    'messaging.attachments': true,
    reports: false,
    'reports.view': false,
    'reports.export': false,
    'payroll.view': false,
    'payroll.manage': false,
  },
};

async function migrate() {
  console.log('🔄 Starting Safe Migration of User Roles & Permissions in Supabase PostgreSQL...');

  const users = await prisma.user.findMany({
    include: { employee: true, permissions: true },
  });

  for (const user of users) {
    const targetRole = ROLE_MAPPINGS[user.email] || 'OPERATION_HEAD';
    console.log(`Updating User ${user.email} (${user.employee?.name || 'No Employee'}) -> Role: ${targetRole}`);

    // Update User Role
    await prisma.user.update({
      where: { id: user.id },
      data: { role: targetRole },
    });

    // Update Permissions
    const permissions = PERMISSIONS_BY_ROLE[targetRole] || PERMISSIONS_BY_ROLE.OPERATION_HEAD;
    for (const [featureKey, enabled] of Object.entries(permissions)) {
      await prisma.userPermission.upsert({
        where: {
          userId_featureKey: {
            userId: user.id,
            featureKey,
          },
        },
        update: { enabled, updatedBy: 'System Migration' },
        create: {
          userId: user.id,
          featureKey,
          enabled,
          updatedBy: 'System Migration',
        },
      });
    }
  }

  console.log('✅ Successfully migrated all users to the official 5-role system!');
}

migrate()
  .catch((err) => {
    console.error('❌ Migration failed:', err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
