// Swaati Enterprises CRM - Standardized Mock Data & Initial State

export const FEATURE_PERMISSIONS_SCHEMA = [
  {
    key: 'dashboard',
    label: 'Dashboard',
    description: 'Overview metrics, daily activity summaries, and quick action cards',
    actions: [
      { key: 'dashboard.view', label: 'View Dashboard Metrics', desc: 'Access operational dashboard and metrics' },
    ],
  },
  {
    key: 'attendance',
    label: 'Daily Attendance',
    description: 'Attendance tracking, shift timings, check-in and check-out logs',
    actions: [
      { key: 'attendance.view_own', label: 'View Own Attendance', desc: 'View self attendance logs and monthly calendar' },
      { key: 'attendance.checkin', label: 'Mark Attendance (Check In / Out)', desc: 'Record daily shift check-in and check-out' },
      { key: 'attendance.view_team', label: 'View Team Attendance', desc: 'View attendance records of all team members' },
      { key: 'attendance.edit', label: 'Request Shift Correction', desc: 'Submit attendance and timing correction requests' },
      { key: 'attendance.approve', label: 'Approve Attendance Corrections', desc: 'Review, modify, and approve employee attendance edits' },
    ],
  },
  {
    key: 'leave',
    label: 'Leave Management',
    description: 'Leave applications, approvals, balance tracking, and absence records',
    actions: [
      { key: 'leave.view_own', label: 'View Own Leaves', desc: 'Track self leave balances and application status' },
      { key: 'leave.apply', label: 'Apply for Leave', desc: 'Submit new leave requests' },
      { key: 'leave.view_team', label: 'View Team Leaves', desc: 'View company leave calendar and team absence requests' },
      { key: 'leave.approve', label: 'Approve Leave Applications', desc: 'Approve pending team leave requests' },
      { key: 'leave.reject', label: 'Reject Leave Applications', desc: 'Reject leave requests with remarks' },
      { key: 'leave.cancel', label: 'Cancel Own Pending Leaves', desc: 'Withdraw pending leave applications' },
    ],
  },
  {
    key: 'tasks',
    label: 'Tasks',
    description: 'Work assignments, operational workflows, progress tracking and discussions',
    actions: [
      { key: 'tasks.view_own', label: 'View Assigned Tasks', desc: 'View tasks assigned to oneself' },
      { key: 'tasks.view_team', label: 'View All / Team Tasks', desc: 'View all company and departmental tasks' },
      { key: 'tasks.create', label: 'Create New Tasks', desc: 'Create and assign tasks to team members' },
      { key: 'tasks.assign', label: 'Reassign Tasks', desc: 'Reallocate tasks to other team members' },
      { key: 'tasks.edit', label: 'Edit Task Details', desc: 'Update task titles, descriptions, and deadlines' },
      { key: 'tasks.status', label: 'Update Task Status', desc: 'Change task status (To Do, In Progress, Completed)' },
      { key: 'tasks.comments', label: 'Add Comments & Notes', desc: 'Post progress comments on task threads' },
      { key: 'tasks.delete', label: 'Delete Tasks', desc: 'Permanently remove tasks' },
    ],
  },
  {
    key: 'leads',
    label: 'Leads & Enquiries',
    description: 'Inbound sales inquiries, client follow-up pipeline, and deal tracking',
    actions: [
      { key: 'leads.view', label: 'View Leads & Pipeline', desc: 'Access lead pipeline and enquiry records' },
      { key: 'leads.create', label: 'Add New Enquiries', desc: 'Log new phone or walk-in client enquiries' },
      { key: 'leads.edit', label: 'Edit Enquiry Details', desc: 'Modify requirements, value, and client info' },
      { key: 'leads.status', label: 'Update Lead Stage', desc: 'Move leads across pipeline stages (New -> Won)' },
      { key: 'leads.assign', label: 'Assign Leads', desc: 'Assign leads to sales engineers' },
      { key: 'leads.delete', label: 'Delete Enquiries', desc: 'Archive or remove enquiry records' },
    ],
  },
  {
    key: 'products',
    label: 'Product Datasheets',
    description: 'Centralized product datasheet library, technical PDFs, and downloads',
    actions: [
      { key: 'products.view', label: 'View & Download Datasheets', desc: 'Browse catalog and download technical PDFs' },
      { key: 'products.create', label: 'Add New Products', desc: 'Create new product entries in library' },
      { key: 'products.edit', label: 'Upload & Replace Datasheets', desc: 'Upload new PDF datasheets or update revisions' },
      { key: 'products.delete', label: 'Delete Products / Documents', desc: 'Remove products or archived datasheets' },
    ],
  },
  {
    key: 'notifications',
    label: 'Notifications',
    description: 'Real-time notifications, task reminders, and leave status updates',
    actions: [
      { key: 'notifications.view', label: 'View Notification Alerts', desc: 'Receive real-time notifications in header & drawer' },
      { key: 'notifications.read', label: 'Mark Alerts as Read', desc: 'Clear and mark notifications as read' },
    ],
  },
  {
    key: 'messaging',
    label: 'Internal Messaging',
    description: '1-on-1 team chat, group channels, and internal collaboration',
    actions: [
      { key: 'messaging.view', label: 'View Messages & Channels', desc: 'Access chat channels and direct conversations' },
      { key: 'messaging.send', label: 'Send Direct Messages', desc: 'Participate in team chat conversations' },
      { key: 'messaging.create_group', label: 'Create Group Channels', desc: 'Create new project and team group channels' },
      { key: 'messaging.attachments', label: 'Send & Download Attachments', desc: 'Share images, documents, and files in chat' },
    ],
  },
  {
    key: 'reports',
    label: 'Reports & Analytics',
    description: 'Operational reports, downloadable summaries, and monthly payroll',
    actions: [
      { key: 'reports.view', label: 'View Summary Reports', desc: 'Access operational attendance & task summary charts' },
      { key: 'reports.export', label: 'Export Reports (CSV / Excel)', desc: 'Export monthly performance and attendance logs' },
      { key: 'payroll.view', label: 'View Monthly Payroll', desc: 'Access monthly salary and attendance payroll computations' },
      { key: 'payroll.manage', label: 'Manage Payroll & Adjustments', desc: 'Apply salary deductions and bonuses' },
    ],
  },
];

export const DEFAULT_PERMISSIONS = {
  // L1 Features
  dashboard: true,
  attendance: true,
  leave: true,
  tasks: true,
  leads: true,
  products: true,
  notifications: true,
  messaging: true,
  reports: false,

  // L2 Sub-actions
  'dashboard.view': true,
  'attendance.view_own': true,
  'attendance.checkin': true,
  'attendance.view_team': false,
  'attendance.edit': true,
  'attendance.approve': false,
  'leave.view_own': true,
  'leave.apply': true,
  'leave.view_team': false,
  'leave.approve': false,
  'leave.reject': false,
  'leave.cancel': true,
  'tasks.view_own': true,
  'tasks.view_team': false,
  'tasks.create': false,
  'tasks.assign': false,
  'tasks.edit': false,
  'tasks.status': true,
  'tasks.comments': true,
  'tasks.delete': false,
  'leads.view': true,
  'leads.create': false,
  'leads.edit': false,
  'leads.status': false,
  'leads.assign': false,
  'leads.delete': false,
  'products.view': true,
  'products.create': false,
  'products.edit': false,
  'products.delete': false,
  'notifications.view': true,
  'notifications.read': true,
  'messaging.view': true,
  'messaging.send': true,
  'messaging.create_group': false,
  'messaging.attachments': true,
  'reports.view': false,
  'reports.export': false,
  'payroll.view': false,
  'payroll.manage': false,
};

export const ROLE_PERMISSION_PRESETS = {
  ADMIN: {
    dashboard: true,
    'dashboard.view': true,
    attendance: true,
    'attendance.view_own': true,
    'attendance.checkin': true,
    'attendance.view_team': true,
    'attendance.edit': true,
    'attendance.approve': true,
    leave: true,
    'leave.view_own': true,
    'leave.apply': true,
    'leave.view_team': true,
    'leave.approve': true,
    'leave.reject': true,
    'leave.cancel': true,
    tasks: true,
    'tasks.view_own': true,
    'tasks.view_team': true,
    'tasks.create': true,
    'tasks.assign': true,
    'tasks.edit': true,
    'tasks.status': true,
    'tasks.comments': true,
    'tasks.delete': true,
    leads: true,
    'leads.view': true,
    'leads.create': true,
    'leads.edit': true,
    'leads.status': true,
    'leads.assign': true,
    'leads.delete': true,
    products: true,
    'products.view': true,
    'products.create': true,
    'products.edit': true,
    'products.delete': true,
    notifications: true,
    'notifications.view': true,
    'notifications.read': true,
    messaging: true,
    'messaging.view': true,
    'messaging.send': true,
    'messaging.create_group': true,
    'messaging.attachments': true,
    reports: true,
    'reports.view': true,
    'reports.export': true,
    'payroll.view': true,
    'payroll.manage': true,
  },
  OPERATION_HEAD: {
    dashboard: true,
    'dashboard.view': true,
    attendance: true,
    'attendance.view_own': true,
    'attendance.checkin': true,
    'attendance.view_team': true,
    'attendance.edit': true,
    'attendance.approve': true,
    leave: true,
    'leave.view_own': true,
    'leave.apply': true,
    'leave.view_team': true,
    'leave.approve': true,
    'leave.reject': true,
    'leave.cancel': true,
    tasks: true,
    'tasks.view_own': true,
    'tasks.view_team': true,
    'tasks.create': true,
    'tasks.assign': true,
    'tasks.edit': true,
    'tasks.status': true,
    'tasks.comments': true,
    'tasks.delete': false,
    leads: true,
    'leads.view': true,
    'leads.create': true,
    'leads.edit': true,
    'leads.status': true,
    'leads.assign': true,
    'leads.delete': false,
    products: true,
    'products.view': true,
    'products.create': false,
    'products.edit': false,
    'products.delete': false,
    notifications: true,
    'notifications.view': true,
    'notifications.read': true,
    messaging: true,
    'messaging.view': true,
    'messaging.send': true,
    'messaging.create_group': true,
    'messaging.attachments': true,
    reports: true,
    'reports.view': true,
    'reports.export': true,
    'payroll.view': false,
    'payroll.manage': false,
  },
  SALES: {
    dashboard: true,
    'dashboard.view': true,
    attendance: true,
    'attendance.view_own': true,
    'attendance.checkin': true,
    'attendance.view_team': false,
    'attendance.edit': true,
    'attendance.approve': false,
    leave: true,
    'leave.view_own': true,
    'leave.apply': true,
    'leave.view_team': false,
    'leave.approve': false,
    'leave.reject': false,
    'leave.cancel': true,
    tasks: true,
    'tasks.view_own': true,
    'tasks.view_team': false,
    'tasks.create': false,
    'tasks.assign': false,
    'tasks.edit': false,
    'tasks.status': true,
    'tasks.comments': true,
    'tasks.delete': false,
    leads: true,
    'leads.view': true,
    'leads.create': true,
    'leads.edit': true,
    'leads.status': true,
    'leads.assign': false,
    'leads.delete': false,
    products: true,
    'products.view': true,
    'products.create': false,
    'products.edit': false,
    'products.delete': false,
    notifications: true,
    'notifications.view': true,
    'notifications.read': true,
    messaging: true,
    'messaging.view': true,
    'messaging.send': true,
    'messaging.create_group': false,
    'messaging.attachments': true,
    reports: false,
    'reports.view': false,
    'reports.export': false,
    'payroll.view': false,
    'payroll.manage': false,
  },
  ACCOUNTANT: {
    dashboard: true,
    'dashboard.view': true,
    attendance: true,
    'attendance.view_own': true,
    'attendance.checkin': true,
    'attendance.view_team': false,
    'attendance.edit': true,
    'attendance.approve': false,
    leave: true,
    'leave.view_own': true,
    'leave.apply': true,
    'leave.view_team': false,
    'leave.approve': false,
    'leave.reject': false,
    'leave.cancel': true,
    tasks: true,
    'tasks.view_own': true,
    'tasks.view_team': false,
    'tasks.create': false,
    'tasks.assign': false,
    'tasks.edit': false,
    'tasks.status': true,
    'tasks.comments': true,
    'tasks.delete': false,
    leads: false,
    'leads.view': false,
    'leads.create': false,
    'leads.edit': false,
    'leads.status': false,
    'leads.assign': false,
    'leads.delete': false,
    products: false,
    'products.view': false,
    'products.create': false,
    'products.edit': false,
    'products.delete': false,
    notifications: true,
    'notifications.view': true,
    'notifications.read': true,
    messaging: true,
    'messaging.view': true,
    'messaging.send': true,
    'messaging.create_group': false,
    'messaging.attachments': true,
    reports: true,
    'reports.view': false,
    'reports.export': true,
    'payroll.view': true,
    'payroll.manage': false,
  },
  WAREHOUSE_MANAGER: {
    dashboard: true,
    'dashboard.view': true,
    attendance: true,
    'attendance.view_own': true,
    'attendance.checkin': true,
    'attendance.view_team': false,
    'attendance.edit': true,
    'attendance.approve': false,
    leave: true,
    'leave.view_own': true,
    'leave.apply': true,
    'leave.view_team': false,
    'leave.approve': false,
    'leave.reject': false,
    'leave.cancel': true,
    tasks: true,
    'tasks.view_own': true,
    'tasks.view_team': false,
    'tasks.create': false,
    'tasks.assign': false,
    'tasks.edit': false,
    'tasks.status': true,
    'tasks.comments': true,
    'tasks.delete': false,
    leads: false,
    'leads.view': false,
    'leads.create': false,
    'leads.edit': false,
    'leads.status': false,
    'leads.assign': false,
    'leads.delete': false,
    products: true,
    'products.view': true,
    'products.create': true,
    'products.edit': true,
    'products.delete': false,
    notifications: true,
    'notifications.view': true,
    'notifications.read': true,
    messaging: true,
    'messaging.view': true,
    'messaging.send': true,
    'messaging.create_group': false,
    'messaging.attachments': true,
    reports: false,
    'reports.view': false,
    'reports.export': false,
    'payroll.view': false,
    'payroll.manage': false,
  },
};


export const INITIAL_EMPLOYEES = [
  {
    id: 'EMP-101',
    userId: 'admin',
    name: 'Shailendra Patil',
    email: 'admin@swaatienterprises.in',
    mobile: '+91 93700 11133',
    role: 'ADMIN',
    department: 'Executive Management',
    designation: 'Founder & Managing Director',
    status: 'Active',
    joiningDate: '2006-04-15',
    reportingManager: 'Self',
    avatar: 'SP',
    idCardType: 'Aadhaar Card',
    idCardNumber: 'XXXX-XXXX-4589',
    idCardFrontUrl: '/images/id-aadhaar-front.png',
    idCardBackUrl: '/images/id-aadhaar-back.png',
    permissions: {
      dashboard: true,
      attendance: true,
      leave: true,
      tasks: true,
      leads: true,
      products: true,
      notifications: true,
      messaging: true,
      reports: true,
    },
  },
  {
    id: 'EMP-102',
    userId: 'rajesh.s',
    name: 'Rajesh Sharma',
    email: 'rajesh.sharma@swaatienterprises.in',
    mobile: '+91 98220 12345',
    role: 'EMPLOYEE',
    department: 'Sales & Business Dev',
    designation: 'Senior Sales Executive',
    status: 'Active',
    joiningDate: '2015-08-10',
    reportingManager: 'Shailendra Patil',
    avatar: 'RS',
    idCardType: 'PAN Card',
    idCardNumber: 'ABCPS1234F',
    idCardFrontUrl: '/images/id-pan-front.png',
    idCardBackUrl: null,
    permissions: {
      dashboard: true,
      attendance: true,
      leave: true,
      tasks: true,
      leads: true,
      products: true,
      notifications: true,
      messaging: true,
      reports: false,
    },
  },
  {
    id: 'EMP-103',
    userId: 'priya.d',
    name: 'Priya Deshmukh',
    email: 'priya.deshmukh@swaatienterprises.in',
    mobile: '+91 98901 23456',
    role: 'EMPLOYEE',
    department: 'Technical & Operations',
    designation: 'Technical Operations Lead',
    status: 'Active',
    joiningDate: '2018-02-01',
    reportingManager: 'Shailendra Patil',
    avatar: 'PD',
    idCardType: 'Aadhaar Card',
    idCardNumber: 'XXXX-XXXX-8921',
    idCardFrontUrl: '/images/id-aadhaar-front.png',
    idCardBackUrl: '/images/id-aadhaar-back.png',
    permissions: {
      dashboard: true,
      attendance: true,
      leave: true,
      tasks: true,
      leads: true,
      products: true,
      notifications: true,
      messaging: true,
      reports: true,
    },
  },
  {
    id: 'EMP-104',
    userId: 'amit.v',
    name: 'Amit Verma',
    email: 'amit.verma@swaatienterprises.in',
    mobile: '+91 97654 32109',
    role: 'EMPLOYEE',
    department: 'Site Execution',
    designation: 'Senior Site Engineer',
    status: 'Active',
    joiningDate: '2020-11-15',
    reportingManager: 'Priya Deshmukh',
    avatar: 'AV',
    idCardType: 'Driving License',
    idCardNumber: 'MH14-2020004587',
    idCardFrontUrl: '/images/id-dl-front.png',
    idCardBackUrl: null,
    permissions: {
      dashboard: true,
      attendance: true,
      leave: true,
      tasks: true,
      leads: false, // Restricted leads for demonstration
      products: true,
      notifications: true,
      messaging: true,
      reports: false,
    },
  },
  {
    id: 'EMP-105',
    userId: 'vikram.j',
    name: 'Vikram Joshi',
    email: 'vikram.joshi@swaatienterprises.in',
    mobile: '+91 91234 56789',
    role: 'EMPLOYEE',
    department: 'Site Execution',
    designation: 'Technical Applicator Specialist',
    status: 'Active',
    joiningDate: '2021-06-20',
    reportingManager: 'Amit Verma',
    avatar: 'VJ',
    idCardType: 'Aadhaar Card',
    idCardNumber: 'XXXX-XXXX-6632',
    idCardFrontUrl: '/images/id-aadhaar-front.png',
    idCardBackUrl: null,
    permissions: {
      dashboard: true,
      attendance: true,
      leave: true,
      tasks: true,
      leads: false,
      products: true,
      notifications: true,
      messaging: true,
      reports: false,
    },
  },
  {
    id: 'EMP-106',
    userId: 'sunita.r',
    name: 'Sunita Rao',
    email: 'sunita.rao@swaatienterprises.in',
    mobile: '+91 94223 89012',
    role: 'EMPLOYEE',
    department: 'Customer Support',
    designation: 'Client Relationship Officer',
    status: 'Inactive', // Deactivated for demonstration
    joiningDate: '2022-01-10',
    reportingManager: 'Shailendra Patil',
    avatar: 'SR',
    idCardType: 'Voter ID',
    idCardNumber: 'VTR-PN-98741',
    idCardFrontUrl: null,
    idCardBackUrl: null,
    permissions: {
      dashboard: true,
      attendance: true,
      leave: true,
      tasks: true,
      leads: true,
      products: true,
      notifications: true,
      messaging: true,
      reports: false,
    },
  },
];

export const INITIAL_ATTENDANCE = [
  {
    id: 'ATT-2026-08-22-101',
    date: '2026-08-22',
    employeeId: 'EMP-101',
    employeeName: 'Shailendra Patil',
    checkIn: '09:45 AM',
    checkOut: '06:15 PM',
    workingHours: '8.5 hrs',
    status: 'Present',
    isLate: false,
    lateMinutes: 0,
  },
  {
    id: 'ATT-2026-08-22-102',
    date: '2026-08-22',
    employeeId: 'EMP-102',
    employeeName: 'Rajesh Sharma',
    checkIn: '10:18 AM',
    checkOut: '06:30 PM',
    workingHours: '8.2 hrs',
    status: 'Late',
    isLate: true,
    lateMinutes: 18,
  },
  {
    id: 'ATT-2026-08-22-103',
    date: '2026-08-22',
    employeeId: 'EMP-103',
    employeeName: 'Priya Deshmukh',
    checkIn: '09:50 AM',
    checkOut: '06:00 PM',
    workingHours: '8.1 hrs',
    status: 'Present',
    isLate: false,
    lateMinutes: 0,
  },
  {
    id: 'ATT-2026-08-22-104',
    date: '2026-08-22',
    employeeId: 'EMP-104',
    employeeName: 'Amit Verma',
    checkIn: '10:35 AM',
    checkOut: '06:45 PM',
    workingHours: '8.1 hrs',
    status: 'Late',
    isLate: true,
    lateMinutes: 35,
  },
  {
    id: 'ATT-2026-08-22-105',
    date: '2026-08-22',
    employeeId: 'EMP-105',
    employeeName: 'Vikram Joshi',
    checkIn: '09:55 AM',
    checkOut: '06:00 PM',
    workingHours: '8.0 hrs',
    status: 'Present',
    isLate: false,
    lateMinutes: 0,
  },
  {
    id: 'ATT-2026-08-22-106',
    date: '2026-08-22',
    employeeId: 'EMP-106',
    employeeName: 'Sunita Rao',
    checkIn: '-',
    checkOut: '-',
    workingHours: '0 hrs',
    status: 'Absent',
    isLate: false,
    lateMinutes: 0,
  },
];

export const INITIAL_LEAVES = [
  {
    id: 'LV-2026-01',
    employeeId: 'EMP-104',
    employeeName: 'Amit Verma',
    leaveType: 'Casual Leave',
    startDate: '2026-08-25',
    endDate: '2026-08-26',
    totalDays: 2,
    reason: 'Family event and personal travel to home town.',
    status: 'Pending',
    appliedDate: '2026-08-22',
    adminRemarks: '',
  },
  {
    id: 'LV-2026-02',
    employeeId: 'EMP-105',
    employeeName: 'Vikram Joshi',
    leaveType: 'Sick Leave',
    startDate: '2026-08-18',
    endDate: '2026-08-18',
    totalDays: 1,
    reason: 'Viral fever and doctor consultation.',
    status: 'Approved',
    appliedDate: '2026-08-17',
    adminRemarks: 'Approved. Take rest.',
  },
  {
    id: 'LV-2026-03',
    employeeId: 'EMP-102',
    employeeName: 'Rajesh Sharma',
    leaveType: 'Earned Leave',
    startDate: '2026-09-01',
    endDate: '2026-09-05',
    totalDays: 5,
    reason: 'Annual family pilgrimage.',
    status: 'Pending',
    appliedDate: '2026-08-20',
    adminRemarks: '',
  },
];

export const INITIAL_TASKS = [
  {
    id: 'TSK-501',
    taskCode: 'TSK-501',
    title: 'Site Inspection at Godrej Emerald Bay Podium Slab',
    description: 'Conduct dampness core test and surface moisture inspection before applying crystalline waterproofing membrane.',
    assignedTo: 'Amit Verma',
    assignedToId: 'EMP-104',
    assignedBy: 'Priya Deshmukh',
    assignedById: 'EMP-103',
    priority: 'High',
    status: 'In Progress',
    startDate: '2026-08-20',
    deadline: '2026-08-24',
    reminder: '1 day before deadline',
    comments: [
      { id: 'c1', author: 'Priya Deshmukh', text: 'Please ensure photo logs of cracks are uploaded.', time: 'Yesterday' },
      { id: 'c2', author: 'Amit Verma', text: 'Site visit completed, preparing dampness report.', time: '2 hours ago' },
    ],
  },
  {
    id: 'TSK-502',
    taskCode: 'TSK-502',
    title: 'Submit Technical Datasheets to L&T Metro Engineers',
    description: 'Compile non-shrink grout test certificates, ASTM compliance sheets, and pull-out test reports for pier cap approval.',
    assignedTo: 'Priya Deshmukh',
    assignedToId: 'EMP-103',
    assignedBy: 'Shailendra Patil',
    assignedById: 'EMP-101',
    priority: 'Urgent',
    status: 'To Do',
    startDate: '2026-08-22',
    deadline: '2026-08-23',
    reminder: 'On deadline day',
    comments: [],
  },
  {
    id: 'TSK-503',
    taskCode: 'TSK-503',
    title: 'Epoxy SL Trial Application at Tata Motors Shop Floor',
    description: 'Execute 100 sq.m sample patch demonstration for plant maintenance heads at Chinchwad Line 3.',
    assignedTo: 'Vikram Joshi',
    assignedToId: 'EMP-105',
    assignedBy: 'Rajesh Sharma',
    assignedById: 'EMP-102',
    priority: 'High',
    status: 'Completed',
    startDate: '2026-08-18',
    deadline: '2026-08-20',
    reminder: '1 day before deadline',
    comments: [
      { id: 'c3', author: 'Vikram Joshi', text: 'Patch completed and curing nicely. Client head gave positive remarks.', time: 'Aug 20' }
    ],
  },
  {
    id: 'TSK-504',
    taskCode: 'TSK-504',
    title: 'Follow-up Call with Kirloskar ETP Tank Project',
    description: 'Confirm site readiness and surface preparation checklist for next week polyurethane coating application.',
    assignedTo: 'Rajesh Sharma',
    assignedToId: 'EMP-102',
    assignedBy: 'Shailendra Patil',
    assignedById: 'EMP-101',
    priority: 'Medium',
    status: 'To Do',
    startDate: '2026-08-22',
    deadline: '2026-08-25',
    reminder: '2 days before deadline',
    comments: [],
  },
  {
    id: 'TSK-505',
    taskCode: 'TSK-505',
    title: 'Monthly Admixture Drum Inventory Audit',
    description: 'Verify warehouse drum counts of Fosroc Superguard, Dr. Fixit Newcoat, and Sika Grout 214.',
    assignedTo: 'Amit Verma',
    assignedToId: 'EMP-104',
    assignedBy: 'Shailendra Patil',
    assignedById: 'EMP-101',
    priority: 'Low',
    status: 'Overdue',
    startDate: '2026-08-10',
    deadline: '2026-08-18',
    reminder: 'On deadline day',
    comments: [],
  },
];

export const INITIAL_LEADS = [
  {
    id: 'LEAD-2026-001',
    leadCode: 'LEAD-2026-001',
    leadName: 'Milind Soman (Project Head)',
    companyName: 'Godrej Properties Ltd',
    mobileNumber: '+91 98230 44123',
    email: 'm.soman@godrejproperties.com',
    location: 'Hinjewadi Phase 2, Pune',
    productInterested: 'Waterproofing Systems (Terrace & Podium)',
    requirement: 'Complete membrane & crystalline waterproofing for 45,000 sq.ft podium slab.',
    source: 'Website',
    leadAddedBy: 'Website Form (Auto)',
    assignedTo: 'Rajesh Sharma',
    assignedToId: 'EMP-102',
    assignedBy: 'Shailendra Patil',
    status: 'Quotation Sent',
    priority: 'High',
    notes: 'Quotation for ₹45 Lakhs submitted. Awaiting commercial sign-off.',
    followUpDate: '2026-08-26',
    createdDate: '2026-08-15',
  },
  {
    id: 'LEAD-2026-002',
    leadCode: 'LEAD-2026-002',
    leadName: 'Suresh Menon (Plant Maintenance Mgr)',
    companyName: 'Tata Motors Limited',
    mobileNumber: '+91 99221 88321',
    email: 'suresh.menon@tatamotors.com',
    location: 'Chinchwad Plant, Pune',
    productInterested: 'Epoxy Flooring HD (Heavy Duty 2mm)',
    requirement: 'Anti-skid chemical resistant floor coating for Assembly Line 3 (12,000 sq.m).',
    source: 'WhatsApp',
    leadAddedBy: 'Rajesh Sharma',
    assignedTo: 'Amit Verma',
    assignedToId: 'EMP-104',
    assignedBy: 'Rajesh Sharma',
    status: 'Follow-up',
    priority: 'High',
    notes: 'Sample patch demonstration completed. Client reviewing quotation.',
    followUpDate: '2026-08-24',
    createdDate: '2026-08-18',
  },
  {
    id: 'LEAD-2026-003',
    leadCode: 'LEAD-2026-003',
    leadName: 'Anand Kulkarni (Chief Engineer)',
    companyName: 'Pune Metro Rail Project (L&T JV)',
    mobileNumber: '+91 94210 99887',
    email: 'a.kulkarni@ltmetro.in',
    location: 'Shivajinagar Section 4, Pune',
    productInterested: 'Structural Repair & Non-Shrink Grouts',
    requirement: 'High compressive non-shrink grouting for 120 pier cap baseplates.',
    source: 'Referral',
    leadAddedBy: 'Shailendra Patil',
    assignedTo: 'Priya Deshmukh',
    assignedToId: 'EMP-103',
    assignedBy: 'Shailendra Patil',
    status: 'Won',
    priority: 'Urgent',
    notes: 'Purchase order of ₹82 Lakhs issued. Supply schedule underway.',
    followUpDate: '2026-08-30',
    createdDate: '2026-07-28',
  },
  {
    id: 'LEAD-2026-004',
    leadCode: 'LEAD-2026-004',
    leadName: 'Rohan Deshpande (Facility Lead)',
    companyName: 'Kirloskar Oil Engines Ltd',
    mobileNumber: '+91 98812 33445',
    email: 'r.deshpande@kirloskar.com',
    location: 'Khadki, Pune',
    productInterested: 'Specialized Coatings & PU Linings',
    requirement: 'Corrosion protective lining for industrial effluent treatment holding tanks.',
    source: 'Website',
    leadAddedBy: 'Website Form (Auto)',
    assignedTo: 'Rajesh Sharma',
    assignedToId: 'EMP-102',
    assignedBy: 'Shailendra Patil',
    status: 'New',
    priority: 'Medium',
    notes: 'Inquiry received via website contact form yesterday.',
    followUpDate: '2026-08-23',
    createdDate: '2026-08-21',
  },
  {
    id: 'LEAD-2026-005',
    leadCode: 'LEAD-2026-005',
    leadName: 'Gaurav Mehta (Admin Head)',
    companyName: 'Panchshil Realty Business Park',
    mobileNumber: '+91 97300 77665',
    email: 'gmehta@panchshil.com',
    location: 'Viman Nagar, Pune',
    productInterested: 'Building & Joint Sealants (PU)',
    requirement: 'Expansion joint sealing across 5-level commercial parking podium.',
    source: 'Call',
    leadAddedBy: 'Rajesh Sharma',
    assignedTo: 'Amit Verma',
    assignedToId: 'EMP-104',
    assignedBy: 'Rajesh Sharma',
    status: 'Contacted',
    priority: 'Medium',
    notes: 'Sent technical datasheet and rate card.',
    followUpDate: '2026-08-25',
    createdDate: '2026-08-19',
  },
];

export const INITIAL_PRODUCTS = [
  {
    id: 'PROD-01',
    productCode: 'PROD-WP-01',
    name: 'Fosroc Superguard Waterproofing Membrane',
    brand: 'Fosroc',
    category: 'Waterproofing Systems',
    productType: 'Cementitious Acrylic Membrane',
    subcategory: 'Elastomeric Barrier',
    status: 'Active',
    documents: [
      {
        id: 'DOC-101',
        title: 'Technical Datasheet (TDS)',
        docType: 'Datasheet',
        fileName: 'Fosroc_Superguard_TDS_v2.1.pdf',
        fileSize: '1.4 MB',
        version: 'v2.1',
        uploadedBy: 'Shailendra Patil',
        uploadedDate: '2026-08-15',
        fileUrl: '/datasheets/Fosroc_Superguard_TDS.pdf',
      },
      {
        id: 'DOC-102',
        title: 'Application Method Statement',
        docType: 'Brochure',
        fileName: 'Fosroc_Method_Statement_2026.pdf',
        fileSize: '2.1 MB',
        version: 'v1.0',
        uploadedBy: 'Priya Deshmukh',
        uploadedDate: '2026-08-10',
        fileUrl: '/datasheets/Fosroc_Method_Statement.pdf',
      },
    ],
  },
  {
    id: 'PROD-02',
    productCode: 'PROD-WP-02',
    name: 'Dr. Fixit Newcoat ETP Elastomeric',
    brand: 'Dr. Fixit',
    category: 'Waterproofing Systems',
    productType: 'Reinforced Liquid Membrane',
    subcategory: 'Roof & Terrace',
    status: 'Active',
    documents: [
      {
        id: 'DOC-201',
        title: 'Technical Datasheet',
        docType: 'Datasheet',
        fileName: 'DrFixit_Newcoat_TDS_v3.pdf',
        fileSize: '890 KB',
        version: 'v3.0',
        uploadedBy: 'Shailendra Patil',
        uploadedDate: '2026-08-05',
        fileUrl: '/datasheets/DrFixit_Newcoat_TDS.pdf',
      },
    ],
  },
  {
    id: 'PROD-03',
    productCode: 'PROD-FL-01',
    name: 'SWAATI EPOXY SL Heavy Duty 2mm',
    brand: 'Swaati Systems',
    category: 'Epoxy Flooring',
    productType: 'Self-Leveling Epoxy',
    subcategory: 'Industrial Grade',
    status: 'Active',
    documents: [
      {
        id: 'DOC-301',
        title: 'Technical Datasheet & Chemical Resistance Table',
        docType: 'Datasheet',
        fileName: 'Swaati_Epoxy_SL_TDS_2026.pdf',
        fileSize: '1.8 MB',
        version: 'v2.4',
        uploadedBy: 'Shailendra Patil',
        uploadedDate: '2026-08-12',
        fileUrl: '/datasheets/Swaati_Epoxy_SL_TDS.pdf',
      },
    ],
  },
  {
    id: 'PROD-04',
    productCode: 'PROD-GR-01',
    name: 'Sika Grout 214 High Precision Non-Shrink',
    brand: 'Sika',
    category: 'Grouts & Anchors',
    productType: 'Cementitious Precision Grout',
    subcategory: 'Machine Base & Pier Caps',
    status: 'Active',
    documents: [
      {
        id: 'DOC-401',
        title: 'Technical Datasheet & Test Certificate',
        docType: 'Datasheet',
        fileName: 'Sika_Grout_214_TDS_v4.pdf',
        fileSize: '1.2 MB',
        version: 'v4.0',
        uploadedBy: 'Priya Deshmukh',
        uploadedDate: '2026-07-22',
        fileUrl: '/datasheets/Sika_Grout_214_TDS.pdf',
      },
    ],
  },
  {
    id: 'PROD-05',
    productCode: 'PROD-AD-01',
    name: 'MYK Arment Concrete Admixture GP High Range',
    brand: 'MYK Arment',
    category: 'Concrete Admixtures',
    productType: 'Superplasticizer PCE Base',
    subcategory: 'High Performance Slump Retention',
    status: 'Active',
    documents: [
      {
        id: 'DOC-501',
        title: 'Technical Specification Sheet',
        docType: 'Datasheet',
        fileName: 'MYK_Admixture_TDS_v1.pdf',
        fileSize: '950 KB',
        version: 'v1.2',
        uploadedBy: 'Shailendra Patil',
        uploadedDate: '2026-08-01',
        fileUrl: '/datasheets/MYK_Admixture_TDS.pdf',
      },
    ],
  },
];

export const INITIAL_NOTIFICATIONS = [
  {
    id: 'NOTIF-01',
    title: 'New Website Lead Received',
    message: 'Kirloskar Oil Engines Ltd enquiry submitted via website contact form.',
    time: '15 mins ago',
    unread: true,
    type: 'lead',
  },
  {
    id: 'NOTIF-02',
    title: 'Leave Request Submitted',
    message: 'Amit Verma requested 2 days Casual Leave starting Aug 25.',
    time: '1 hour ago',
    unread: true,
    type: 'leave',
  },
  {
    id: 'NOTIF-03',
    title: 'Task Overdue Alert',
    message: 'Monthly Admixture Drum Inventory Audit is overdue.',
    time: '3 hours ago',
    unread: true,
    type: 'task',
  },
  {
    id: 'NOTIF-04',
    title: 'Late Check-in Recorded',
    message: 'Amit Verma checked in at 10:35 AM (Late by 35 mins).',
    time: 'Today 10:35 AM',
    unread: false,
    type: 'attendance',
  },
];

export const INITIAL_GROUPS = [
  {
    id: 'GRP-1',
    name: 'Technical & Site Operations',
    description: 'Site engineers, moisture testing & technical applicator team',
    memberIds: ['EMP-101', 'EMP-103', 'EMP-104', 'EMP-105'],
    createdBy: 'Shailendra Patil',
    createdAt: '2026-08-10',
    avatar: 'TS',
  },
  {
    id: 'GRP-2',
    name: 'Sales & Project Coordination',
    description: 'Lead follow-ups, client meetings & quotation tracking',
    memberIds: ['EMP-101', 'EMP-102', 'EMP-103'],
    createdBy: 'Shailendra Patil',
    createdAt: '2026-08-12',
    avatar: 'SC',
  },
];

export const INITIAL_MESSAGES = [
  {
    id: 'MSG-1',
    senderId: 'EMP-101',
    senderName: 'Shailendra Patil',
    recipientId: 'EMP-104',
    recipientName: 'Amit Verma',
    text: 'Amit, please make sure the Godrej podium dampness test is thoroughly documented today.',
    time: '10:45 AM',
    timestamp: '2026-08-22T10:45:00',
    isRead: true,
  },
  {
    id: 'MSG-2',
    senderId: 'EMP-104',
    senderName: 'Amit Verma',
    recipientId: 'EMP-101',
    recipientName: 'Shailendra Patil',
    text: 'Yes Sir, I am at site now with the digital moisture gauge. Will share pictures by 3 PM.',
    time: '11:02 AM',
    timestamp: '2026-08-22T11:02:00',
    isRead: true,
  },
  {
    id: 'MSG-3',
    senderId: 'EMP-102',
    senderName: 'Rajesh Sharma',
    recipientId: 'EMP-101',
    recipientName: 'Shailendra Patil',
    text: 'Sir, Kirloskar facility manager called regarding ETP lining. Scheduled site visit for Monday.',
    time: '01:30 PM',
    timestamp: '2026-08-22T13:30:00',
    isRead: false,
  },
  {
    id: 'MSG-G1',
    groupId: 'GRP-1',
    senderId: 'EMP-103',
    senderName: 'Priya Deshmukh',
    text: 'Site team: please ensure moisture gauge calibration certificates are carried to the Godrej site today.',
    time: '09:30 AM',
    timestamp: '2026-08-24T09:30:00',
    isRead: true,
  },
  {
    id: 'MSG-G2',
    groupId: 'GRP-1',
    senderId: 'EMP-104',
    senderName: 'Amit Verma',
    text: 'Understood Priya ma’am. Calibration done, readings will be uploaded with photos by 3 PM.',
    time: '09:45 AM',
    timestamp: '2026-08-24T09:45:00',
    isRead: true,
  },
  {
    id: 'MSG-G3',
    groupId: 'GRP-2',
    senderId: 'EMP-102',
    senderName: 'Rajesh Sharma',
    text: 'Kirloskar site visit confirmed for 11 AM next Monday. Quotation drafts ready for review.',
    time: '11:15 AM',
    timestamp: '2026-08-24T11:15:00',
    isRead: true,
  },
];

export const INITIAL_SYSTEM_SETTINGS = {
  companyName: 'Swaati Enterprises',
  officeAddress: 'Office No. 2, Building No. D, Shraddha Garden, Gawade Park, Opp Tata Motors, Chinchwad, Pune – 411033',
  phone1: '+91 93700 11133',
  phone2: '+91 83800 17333',
  email: 'admin@swaatienterprises.in',
  officeStartTime: '10:00 AM', // Configurable office start time
  gracePeriodMinutes: 15,
  workingDaysPerMonth: 26,
};

export const INITIAL_AUDIT_LOGS = [
  {
    id: 'LOG-01',
    action: 'Team Member Created',
    performedBy: 'Shailendra Patil',
    target: 'Amit Verma (EMP-104)',
    time: '2026-08-15 10:00 AM',
  },
  {
    id: 'LOG-02',
    action: 'Datasheet Replaced',
    performedBy: 'Shailendra Patil',
    target: 'Fosroc Superguard TDS (v2.1)',
    time: '2026-08-15 02:30 PM',
  },
  {
    id: 'LOG-03',
    action: 'Leave Approved',
    performedBy: 'Shailendra Patil',
    target: 'Vikram Joshi (Sick Leave - 1 day)',
    time: '2026-08-17 11:15 AM',
  },
  {
    id: 'LOG-04',
    action: 'Team Member Deactivated',
    performedBy: 'Shailendra Patil',
    target: 'Sunita Rao (EMP-106)',
    time: '2026-08-20 04:45 PM',
  },
];
