export const INITIAL_EMPLOYEES = [
  {
    id: 'EMP-101',
    name: 'Shailendra Patil',
    email: 'shailendra.patil@swaatienterprises.in',
    mobile: '+91 93700 11133',
    role: 'ADMIN',
    department: 'Executive Management',
    designation: 'Founder & CEO',
    status: 'Active',
    joiningDate: '2006-04-15',
    avatar: 'SP',
  },
  {
    id: 'EMP-102',
    name: 'Rajesh Sharma',
    email: 'rajesh.sharma@swaatienterprises.in',
    mobile: '+91 98220 12345',
    role: 'MANAGER',
    department: 'Sales & Business Dev',
    designation: 'Sales Manager',
    status: 'Active',
    joiningDate: '2015-08-10',
    avatar: 'RS',
  },
  {
    id: 'EMP-103',
    name: 'Priya Deshmukh',
    email: 'priya.deshmukh@swaatienterprises.in',
    mobile: '+91 98901 23456',
    role: 'MANAGER',
    department: 'Technical & Operations',
    designation: 'Operations Manager',
    status: 'Active',
    joiningDate: '2018-02-01',
    avatar: 'PD',
  },
  {
    id: 'EMP-104',
    name: 'Amit Verma',
    email: 'amit.verma@swaatienterprises.in',
    mobile: '+91 97654 32109',
    role: 'EMPLOYEE',
    department: 'Technical & Operations',
    designation: 'Senior Site Engineer',
    status: 'Active',
    joiningDate: '2020-11-15',
    avatar: 'AV',
  },
  {
    id: 'EMP-105',
    name: 'Vikram Joshi',
    email: 'vikram.joshi@swaatienterprises.in',
    mobile: '+91 91234 56789',
    role: 'EMPLOYEE',
    department: 'Site Execution',
    designation: 'Technical Applicator Lead',
    status: 'Active',
    joiningDate: '2021-06-20',
    avatar: 'VJ',
  },
  {
    id: 'EMP-106',
    name: 'Sunita Rao',
    email: 'sunita.rao@swaatienterprises.in',
    mobile: '+91 94223 89012',
    role: 'EMPLOYEE',
    department: 'Customer Support',
    designation: 'Client Relationship Executive',
    status: 'Active',
    joiningDate: '2022-01-10',
    avatar: 'SR',
  },
];

export const INITIAL_LEADS = [
  {
    id: 'LEAD-2026-001',
    customerCompany: 'Godrej Properties Ltd',
    contactPerson: 'Milind Soman (Project Head)',
    phone: '+91 98230 44123',
    email: 'm.soman@godrejproperties.com',
    productInterested: 'Waterproofing Systems (Terrace & Basement)',
    requirement: 'Complete membrane & crystalline waterproofing for 45,000 sq.ft podium slab at Hinjewadi site.',
    source: 'Website Enquiry',
    assignedTo: 'Rajesh Sharma',
    assignedToId: 'EMP-102',
    status: 'Quotation Sent',
    estimatedValue: 4500000,
    followUpDate: '2026-08-15',
    createdDate: '2026-08-01',
  },
  {
    id: 'LEAD-2026-002',
    customerCompany: 'Tata Motors Chinchwad Plant',
    contactPerson: 'Suresh Menon (Plant Maintenance Mgr)',
    phone: '+91 99221 88321',
    email: 'suresh.menon@tatamotors.com',
    productInterested: 'Epoxy Flooring HD (Heavy Duty)',
    requirement: 'Anti-skid chemical resistant epoxy floor coating for Assembly Line 3 (12,000 sq.m).',
    source: 'Direct Referral',
    assignedTo: 'Amit Verma',
    assignedToId: 'EMP-104',
    status: 'Contacted',
    estimatedValue: 1850000,
    followUpDate: '2026-08-14',
    createdDate: '2026-08-05',
  },
  {
    id: 'LEAD-2026-003',
    customerCompany: 'Pune Metro Rail Expansion (L&T JV)',
    contactPerson: 'Anand Kulkarni (Chief Engineer)',
    phone: '+91 94210 99887',
    email: 'a.kulkarni@ltmetro.in',
    productInterested: 'Structural Repair & Non-Shrink Grouts',
    requirement: 'High compressive non-shrink grouting for pier cap baseplates across Section 4.',
    source: 'Tender / Enterprise',
    assignedTo: 'Priya Deshmukh',
    assignedToId: 'EMP-103',
    status: 'Won',
    estimatedValue: 8200000,
    followUpDate: '2026-08-20',
    createdDate: '2026-07-20',
  },
  {
    id: 'LEAD-2026-004',
    customerCompany: 'Kirloskar Oil Engines Ltd',
    contactPerson: 'Rohan Deshpande (Facility Officer)',
    phone: '+91 98812 33445',
    email: 'r.deshpande@kirloskar.com',
    productInterested: 'Industrial Solutions & Polyurethane Coatings',
    requirement: 'Chemical resistant lining for effluent treatment plant tanks.',
    source: 'Website Enquiry',
    assignedTo: 'Rajesh Sharma',
    assignedToId: 'EMP-102',
    status: 'New',
    estimatedValue: 2400000,
    followUpDate: '2026-08-14',
    createdDate: '2026-08-12',
  },
  {
    id: 'LEAD-2026-005',
    customerCompany: 'Panchshil Realty Business Park',
    contactPerson: 'Gaurav Mehta (Infrastructure Admin)',
    phone: '+91 97300 77665',
    email: 'gmehta@panchshil.com',
    productInterested: 'Building & Joint Sealants',
    requirement: 'Expansion joint sealing using PU sealant across multi-level parking building.',
    source: 'Exhibition',
    assignedTo: 'Amit Verma',
    assignedToId: 'EMP-104',
    status: 'Follow-up',
    estimatedValue: 1200000,
    followUpDate: '2026-08-16',
    createdDate: '2026-08-08',
  },
];

export const INITIAL_TASKS = [
  {
    id: 'TSK-501',
    title: 'Site Inspection at Godrej Emerald Bay Podium Slab',
    description: 'Conduct core inspection and dampness test prior to applying crystalline waterproofing membrane.',
    assignedTo: 'Amit Verma',
    assignedToId: 'EMP-104',
    createdBy: 'Priya Deshmukh',
    priority: 'High',
    status: 'In Progress',
    startDate: '2026-08-12',
    dueDate: '2026-08-14',
    category: 'Site Survey',
  },
  {
    id: 'TSK-502',
    title: 'Submit Technical Datasheets to L&T Metro Engineers',
    description: 'Compile non-shrink grout test certificates and ASTM compliance sheets for pier cap approval.',
    assignedTo: 'Priya Deshmukh',
    assignedToId: 'EMP-103',
    createdBy: 'Shailendra Patil',
    priority: 'Urgent',
    status: 'To Do',
    startDate: '2026-08-13',
    dueDate: '2026-08-14',
    category: 'Documentation',
  },
  {
    id: 'TSK-503',
    title: 'Epoxy SL Trial Application at Tata Motors Shop Floor',
    description: 'Execute 100 sq.m sample patch demonstration for plant heads.',
    assignedTo: 'Vikram Joshi',
    assignedToId: 'EMP-105',
    createdBy: 'Rajesh Sharma',
    priority: 'High',
    status: 'Completed',
    startDate: '2026-08-10',
    dueDate: '2026-08-12',
    category: 'Field Demo',
  },
  {
    id: 'TSK-504',
    title: 'Follow-up Call with Kirloskar ETP Tank Project',
    description: 'Confirm site readiness for site inspection next week.',
    assignedTo: 'Sunita Rao',
    assignedToId: 'EMP-106',
    createdBy: 'Rajesh Sharma',
    priority: 'Medium',
    status: 'To Do',
    startDate: '2026-08-14',
    dueDate: '2026-08-15',
    category: 'Client Call',
  },
  {
    id: 'TSK-505',
    title: 'Monthly Inventory Audit at Chinchwad Warehouse',
    description: 'Verify stock count of Fosroc, Dr. Fixit, and Sika admixture drums.',
    assignedTo: 'Amit Verma',
    assignedToId: 'EMP-104',
    createdBy: 'Shailendra Patil',
    priority: 'Low',
    status: 'Overdue',
    startDate: '2026-08-01',
    dueDate: '2026-08-10',
    category: 'Inventory',
  },
];

export const INITIAL_CUSTOMERS = [
  {
    id: 'CUST-301',
    companyName: 'Godrej Properties Ltd',
    contactPerson: 'Milind Soman',
    phone: '+91 98230 44123',
    email: 'm.soman@godrejproperties.com',
    city: 'Pune',
    assignedEmployee: 'Rajesh Sharma',
    totalProjects: 4,
    status: 'Active Client',
    lastInteraction: '2026-08-12',
  },
  {
    id: 'CUST-302',
    companyName: 'Tata Motors Limited',
    contactPerson: 'Suresh Menon',
    phone: '+91 99221 88321',
    email: 'suresh.menon@tatamotors.com',
    city: 'Chinchwad, Pune',
    assignedEmployee: 'Amit Verma',
    totalProjects: 12,
    status: 'Key Enterprise',
    lastInteraction: '2026-08-10',
  },
  {
    id: 'CUST-303',
    companyName: 'Larsen & Toubro Heavy Engineering',
    contactPerson: 'Anand Kulkarni',
    phone: '+91 94210 99887',
    email: 'a.kulkarni@ltmetro.in',
    city: 'Mumbai / Pune',
    assignedEmployee: 'Priya Deshmukh',
    totalProjects: 8,
    status: 'Key Enterprise',
    lastInteraction: '2026-08-13',
  },
  {
    id: 'CUST-304',
    companyName: 'Kirloskar Oil Engines Ltd',
    contactPerson: 'Rohan Deshpande',
    phone: '+91 98812 33445',
    email: 'r.deshpande@kirloskar.com',
    city: 'Khadki, Pune',
    assignedEmployee: 'Rajesh Sharma',
    totalProjects: 3,
    status: 'Active Client',
    lastInteraction: '2026-08-12',
  },
];

export const INITIAL_FOLLOW_UPS = [
  {
    id: 'FLP-101',
    customer: 'Godrej Properties Ltd',
    product: 'Waterproofing Systems',
    contactPerson: 'Milind Soman',
    phone: '+91 98230 44123',
    assignedTo: 'Rajesh Sharma',
    assignedToId: 'EMP-102',
    followUpDate: '2026-08-14',
    status: 'Pending',
    notes: 'Discuss revised commercial proposal after technical site visit.',
  },
  {
    id: 'FLP-102',
    customer: 'Tata Motors Chinchwad Plant',
    product: 'Epoxy Flooring HD',
    contactPerson: 'Suresh Menon',
    phone: '+91 99221 88321',
    assignedTo: 'Amit Verma',
    assignedToId: 'EMP-104',
    followUpDate: '2026-08-14',
    status: 'Pending',
    notes: 'Review trial application feedback with shop floor manager.',
  },
  {
    id: 'FLP-103',
    customer: 'Panchshil Realty Business Park',
    product: 'Building & Joint Sealants',
    contactPerson: 'Gaurav Mehta',
    phone: '+91 97300 77665',
    assignedTo: 'Amit Verma',
    assignedToId: 'EMP-104',
    followUpDate: '2026-08-13',
    status: 'Completed',
    notes: 'Sample shade approved. Awaiting PO release.',
  },
  {
    id: 'FLP-104',
    customer: 'Kirloskar Oil Engines Ltd',
    product: 'Industrial Solutions',
    contactPerson: 'Rohan Deshpande',
    phone: '+91 98812 33445',
    assignedTo: 'Sunita Rao',
    assignedToId: 'EMP-106',
    followUpDate: '2026-08-11',
    status: 'Missed',
    notes: 'Reschedule site inspection call.',
  },
];

export const INITIAL_ATTENDANCE = [
  {
    id: 'ATT-2026-08-13-101',
    date: '2026-08-13',
    employeeId: 'EMP-101',
    employeeName: 'Shailendra Patil',
    checkIn: '09:00 AM',
    checkOut: '06:15 PM',
    workingHours: '9.2 hrs',
    status: 'Present',
  },
  {
    id: 'ATT-2026-08-13-102',
    date: '2026-08-13',
    employeeId: 'EMP-102',
    employeeName: 'Rajesh Sharma',
    checkIn: '09:12 AM',
    checkOut: '06:00 PM',
    workingHours: '8.8 hrs',
    status: 'Present',
  },
  {
    id: 'ATT-2026-08-13-103',
    date: '2026-08-13',
    employeeId: 'EMP-103',
    employeeName: 'Priya Deshmukh',
    checkIn: '08:55 AM',
    checkOut: '06:30 PM',
    workingHours: '9.5 hrs',
    status: 'Present',
  },
  {
    id: 'ATT-2026-08-13-104',
    date: '2026-08-13',
    employeeId: 'EMP-104',
    employeeName: 'Amit Verma',
    checkIn: '09:40 AM',
    checkOut: '06:10 PM',
    workingHours: '8.5 hrs',
    status: 'Late',
  },
  {
    id: 'ATT-2026-08-13-105',
    date: '2026-08-13',
    employeeId: 'EMP-105',
    employeeName: 'Vikram Joshi',
    checkIn: '09:05 AM',
    checkOut: '05:55 PM',
    workingHours: '8.8 hrs',
    status: 'Present',
  },
  {
    id: 'ATT-2026-08-13-106',
    date: '2026-08-13',
    employeeId: 'EMP-106',
    employeeName: 'Sunita Rao',
    checkIn: '-',
    checkOut: '-',
    workingHours: '0 hrs',
    status: 'On Leave',
  },
];

export const INITIAL_NOTIFICATIONS = [
  {
    id: 'NOTIF-01',
    title: 'New Enterprise Lead Assigned',
    message: 'Kirloskar Oil Engines Ltd enquiry assigned to Rajesh Sharma.',
    time: '10 mins ago',
    unread: true,
    type: 'lead',
  },
  {
    id: 'NOTIF-02',
    title: 'Task Overdue Reminder',
    message: 'Monthly Inventory Audit at Chinchwad Warehouse is overdue.',
    time: '2 hours ago',
    unread: true,
    type: 'task',
  },
  {
    id: 'NOTIF-03',
    title: 'Follow-up Scheduled Today',
    message: 'Follow-up call with Tata Motors Chinchwad plant (Suresh Menon).',
    time: '4 hours ago',
    unread: false,
    type: 'followup',
  },
  {
    id: 'NOTIF-04',
    title: 'Attendance Marked',
    message: 'Amit Verma checked in at 09:40 AM (Status: Late).',
    time: 'Today 09:40 AM',
    unread: false,
    type: 'attendance',
  },
];

export const MOCK_PRODUCTS = [
  {
    id: 'PROD-01',
    name: 'Fosroc Waterproofing Membrane',
    category: 'Waterproofing Systems',
    brand: 'Fosroc',
    status: 'Active',
    datasheet: 'Fosroc_Superguard_TDS.pdf',
    updatedDate: '2026-07-25',
  },
  {
    id: 'PROD-02',
    name: 'Dr. Fixit Newcoat ETP',
    category: 'Waterproofing Systems',
    brand: 'Dr. Fixit',
    status: 'Active',
    datasheet: 'DrFixit_Newcoat_TDS.pdf',
    updatedDate: '2026-08-02',
  },
  {
    id: 'PROD-03',
    name: 'SWAATI EPOXY SL 2mm',
    category: 'Epoxy Flooring',
    brand: 'Swaati Systems',
    status: 'Active',
    datasheet: 'Swaati_Epoxy_SL_TDS.pdf',
    updatedDate: '2026-08-10',
  },
  {
    id: 'PROD-04',
    name: 'Sika Grout 214 Ind',
    category: 'Grouts & Anchors',
    brand: 'Sika',
    status: 'Active',
    datasheet: 'Sika_Grout_214_TDS.pdf',
    updatedDate: '2026-06-18',
  },
  {
    id: 'PROD-05',
    name: 'MYK Arment Concrete Admixture GP',
    category: 'Concrete Admixtures',
    brand: 'MYK Arment',
    status: 'Active',
    datasheet: 'MYK_Admixture_TDS.pdf',
    updatedDate: '2026-08-01',
  },
];
